apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: furnacegroups.furnace.io
spec:
  group: furnace.io
  names:
    kind: FurnaceGroup
    listKind: FurnaceGroupList
    plural: furnacegroups
    singular: furnacegroup
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Name
      type: string
      jsonPath: .spec.name
    - name: Synced
      type: string
      jsonPath: .status.conditions[?(@.type=="Synced")].status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
            - name
            properties:
              name:
                type: string
              displayName:
                type: string
          status:
            type: object
            properties:
              furnaceId:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  - reason
                  - lastTransitionTime
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    observedGeneration:
                      type: integer
                      format: int64
